apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.storeName }}-mysql
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ .Values.storeName }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "woocommerce.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "woocommerce.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.mysql.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: {{ .Values.storeName }}-mysql-secret
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          {{- with .Values.mysql.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mysql.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Values.storeName }}-mysql-pvc
