apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-mysql
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      name: mysql
  selector:
    {{- include "woocommerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
