apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storeName }}-mysql-pvc
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.storage.storageClass }}
  storageClassName: {{ .Values.mysql.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storeName }}-wp-pvc
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.storage.storageClass }}
  storageClassName: {{ .Values.mysql.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 2Gi
