apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storeName }}-mysql-secret
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storeName }}-wp-secret
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  WORDPRESS_DB_HOST: {{ .Values.storeName }}-mysql
  WORDPRESS_DB_NAME: {{ .Values.mysql.database | quote }}
  WORDPRESS_DB_USER: {{ .Values.mysql.user | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mysql.password | quote }}
  WORDPRESS_ADMIN_USER: {{ .Values.wordpress.adminUser | quote }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.wordpress.adminPassword | quote }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.wordpress.adminEmail | quote }}
