apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-wordpress
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "woocommerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
