apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.storeName }}-postgres
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ .Values.storeName }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "medusa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "medusa.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: {{ .Values.postgres.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: {{ .Values.storeName }}-postgres-secret
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          {{- with .Values.postgres.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgres.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.storeName }}-postgres-pvc
