apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-postgres
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    {{- include "medusa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
