{{- if .Values.storefront.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-storefront
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    {{- include "medusa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
{{- end }}
